name: ambulance_system
description: An ambulance ordering system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  cupertino_icons: ^1.0.2
  image_picker: ^1.1.2
  url_launcher: ^6.3.1
  geolocator: ^13.0.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  google_fonts: ^6.2.1
  intl: ^0.19.0
  firebase_auth: ^5.3.1
  dart_firebase_functions: ^0.0.1-dev.1
  flutter_local_notifications: ^17.2.4
  google_maps_flutter: ^2.9.0
  fl_chart: ^0.69.0
  permission_handler: ^11.3.1
  geocoding: ^3.0.0
  firebase_messaging: ^15.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.3.2
flutter:
  uses-material-design: true
  assets:

    - assets/icons/



# Add flutter_launcher_icons configuration at root level
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icons/icon_foreground.png"
  web:
    generate: true
    image_path: "assets/icons/icon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "assets/icons/icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icons/icon.png"