// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCToIWs4DvFlb4JHluv4EcBMUje-75RIxg',
    appId: '1:813934781422:web:229a29301d78261c8864ff',
    messagingSenderId: '813934781422',
    projectId: 'ambulance-app-6d75a',
    authDomain: 'ambulance-app-6d75a.firebaseapp.com',
    storageBucket: 'ambulance-app-6d75a.appspot.com',
    measurementId: 'G-NBN4XZJRVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSeanBp9qoFpP4kCiLAD73usxhpnuAKLI',
    appId: '1:813934781422:android:6127e9c10fb148fe8864ff',
    messagingSenderId: '813934781422',
    projectId: 'ambulance-app-6d75a',
    storageBucket: 'ambulance-app-6d75a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWreyHqh7rzHH7lwXhG8VN2nl8ixKFOpg',
    appId: '1:813934781422:ios:63af3a21150d235c8864ff',
    messagingSenderId: '813934781422',
    projectId: 'ambulance-app-6d75a',
    storageBucket: 'ambulance-app-6d75a.appspot.com',
    iosBundleId: 'com.example.ambulanceSystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCWreyHqh7rzHH7lwXhG8VN2nl8ixKFOpg',
    appId: '1:813934781422:ios:63af3a21150d235c8864ff',
    messagingSenderId: '813934781422',
    projectId: 'ambulance-app-6d75a',
    storageBucket: 'ambulance-app-6d75a.appspot.com',
    iosBundleId: 'com.example.ambulanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCToIWs4DvFlb4JHluv4EcBMUje-75RIxg',
    appId: '1:813934781422:web:e897a2bd20e3a61b8864ff',
    messagingSenderId: '813934781422',
    projectId: 'ambulance-app-6d75a',
    authDomain: 'ambulance-app-6d75a.firebaseapp.com',
    storageBucket: 'ambulance-app-6d75a.appspot.com',
    measurementId: 'G-46FPPQP241',
  );
}
